---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-receipt
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: read-receipt
  template:
    metadata:
      labels:
        app: read-receipt
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: read-receipt
          image: marashisamin/read-receipt:{{TAG}}
          imagePullPolicy: "Always"
          readinessProbe:
            httpGet:
              path: /stats
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3

          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: read-receipt-db
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: read-receipt
            - name: DB_USER
              value: read-receipt
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: read-receipt-secret
                  key: dbpass
---
apiVersion: v1
kind: Service
metadata:
  name: read-receipt
  labels:
    app: read-receipt
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: read-receipt
