variable "ssh_key_private" {
  type = string
}

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  profile = "default"
  region  = "us-west-2"
}

resource "aws_lightsail_static_ip" "k8s_node" {
  name = "k8_node_static_ip"
}

resource "aws_lightsail_instance" "k8s_node" {
  name              = "k8s_node"
  key_pair_name     = "aminm2"
  blueprint_id      = "debian_9_5"
  bundle_id         = "micro_2_0"
  availability_zone = "us-west-2a"
}

resource "aws_lightsail_static_ip_attachment" "k8s_node" {
  static_ip_name = aws_lightsail_static_ip.k8s_node.id
  instance_name  = aws_lightsail_instance.k8s_node.id
}

resource "aws_lightsail_static_ip" "k8s_master" {
  name = "k8_master_static_ip"
}

resource "aws_lightsail_instance" "k8s_master" {
  name              = "k8s_master"
  key_pair_name     = "aminm2"
  blueprint_id      = "debian_9_5"
  bundle_id         = "micro_2_0"
  availability_zone = "us-west-2a"
}

resource "aws_lightsail_static_ip_attachment" "k8s_master" {
  static_ip_name = aws_lightsail_static_ip.k8s_master.id
  instance_name  = aws_lightsail_instance.k8s_master.id
}

resource "local_file" "ansible_group_vars" {
  depends_on  = [aws_lightsail_static_ip.k8s_master, aws_lightsail_static_ip.k8s_node, aws_lightsail_instance.k8s_master, aws_lightsail_instance.k8s_node]
  content     = <<EOF
# This is autogenerated using terraform (DO NOT ADD TO GIT)
---
k3s_version: v1.17.5+k3s1
ansible_user: admin
systemd_dir: /etc/systemd/system
master_ip: "${aws_lightsail_static_ip.k8s_master.ip_address}"
extra_server_args: "--write-kubeconfig-mode 644"
EOF
  filename    = "${path.module}/../../ansible/inventory/group_vars/all.yml"
}

resource "local_file" "ansible_inventory" {
  depends_on  = [aws_lightsail_static_ip.k8s_master, aws_lightsail_static_ip.k8s_node, aws_lightsail_instance.k8s_master, aws_lightsail_instance.k8s_node, local_file.ansible_group_vars]
  content     = <<EOF
# This is autogenerated using terraform (DO NOT ADD TO GIT)
---
all:
  children:
    k3s_cluster:
      hosts:
        ${aws_lightsail_static_ip.k8s_master.ip_address}:
        ${aws_lightsail_static_ip.k8s_node.ip_address}:
    master:
      hosts:
        ${aws_lightsail_static_ip.k8s_master.ip_address}:
    node:
      hosts:
        ${aws_lightsail_static_ip.k8s_node.ip_address}:
EOF
  filename    = "${path.module}/../../ansible/inventory/hosts.yml"
  provisioner "local-exec" {
    command = "aws lightsail --region us-west-2 put-instance-public-ports --instance-name=${aws_lightsail_instance.k8s_master.id} --port-infos fromPort=6443,toPort=6443,protocol=tcp,cidrs=${aws_lightsail_static_ip.k8s_node.ip_address}/32 fromPort=22,toPort=22,protocol=tcp"
  }
  provisioner "local-exec" {
    command = "aws lightsail --region us-west-2 put-instance-public-ports --instance-name=${aws_lightsail_instance.k8s_node.id} --port-infos fromPort=22,toPort=22,protocol=tcp"
  }
  provisioner "local-exec" {
    command = "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u admin -i ../../ansible/inventory --private-key ${var.ssh_key_private} ../../ansible/provision.yml"
  }
}
